initial <- list()

################################################################################
# Settings for Reduced dimension plot 1
################################################################################

initial[["ReducedDimensionPlot1"]] <- new(
    "ReducedDimensionPlot",
    Type = "PCA",
    XAxis = 1L,
    YAxis = 2L,
    ColorBy = "Column data",
    ColorByColumnData = "SpD",
    ColorByFeatureNameAssay = "logcounts",
    ColorBySampleNameColor = "#FF0000",
    FacetRowBy = "None",
    FacetColumnBy = "None",
    FacetRowByColData = "SpD",
    FacetColumnByColData = "SpD",
    ShapeBy = "None",
    SizeBy = "None",
    ShapeByColumnData = "SpD",
    SizeByColumnData = "age",
    TooltipColumnData = character(0),
    ColorByDefaultColor = "#000000",
    ColorByFeatureName = "SHANK3",
    ColorByFeatureSource = "---",
    ColorByFeatureDynamicSource = FALSE,
    ColorBySampleName = "Br1204",
    ColorBySampleSource = "---",
    ColorBySampleDynamicSource = FALSE,
    SelectionAlpha = 0.1,
    ZoomData = numeric(0),
    BrushData = list(),
    VisualBoxOpen = FALSE,
    VisualChoices = "Color",
    ContourAdd = FALSE,
    ContourColor = "#0000FF",
    PointSize = 2,
    PointAlpha = 1,
    Downsample = FALSE,
    DownsampleResolution = 200,
    CustomLabels = FALSE,
    CustomLabelsText = "Br1204",
    FontSize = 2,
    LegendPointSize = 2,
    LegendPosition = "Bottom",
    HoverInfo = TRUE,
    LabelCenters = FALSE,
    LabelCentersBy = "SpD",
    LabelCentersColor = "#000000",
    VersionInfo = list(iSEE = structure(
        list(c(2L, 10L, 0L)),
        class = c(
            "package_version",
            "numeric_version"
        )
    )),
    PanelId = c(ReducedDimensionPlot = 1L),
    PanelHeight = 600L,
    PanelWidth = 5L,
    SelectionBoxOpen = FALSE,
    RowSelectionSource = "---",
    ColumnSelectionSource = "---",
    DataBoxOpen = FALSE,
    RowSelectionDynamicSource = FALSE,
    ColumnSelectionDynamicSource = FALSE,
    RowSelectionRestrict = FALSE,
    ColumnSelectionRestrict = FALSE,
    SelectionHistory = list()
)

################################################################################
# Settings for Complex heatmap 1
################################################################################

initial[["ComplexHeatmapPlot1"]] <- new(
    "ComplexHeatmapPlot",
    Assay = "logcounts",
    CustomRows = TRUE,
    CustomRowsText = "CLDN5\nRELN\nHPCAL1\nFREM3\nGPX3\nTSHZ2\nPCP4\nSMIM32\nFOXO6\nMBP",
    ClusterRows = FALSE,
    ClusterRowsDistance = "spearman",
    ClusterRowsMethod = "ward.D2",
    DataBoxOpen = FALSE,
    VisualChoices = "Annotations",
    ColumnData = c(
        "SpD",
        "subject"
    ),
    RowData = character(0),
    CustomBounds = FALSE,
    LowerBound = NA_real_,
    UpperBound = NA_real_,
    AssayCenterRows = TRUE,
    AssayScaleRows = TRUE,
    DivergentColormap = "blue < white < orange",
    ShowDimNames = "Rows",
    LegendPosition = "Right",
    LegendDirection = "Vertical",
    VisualBoxOpen = FALSE,
    NamesRowFontSize = 12,
    NamesColumnFontSize = 12,
    ShowColumnSelection = TRUE,
    OrderColumnSelection = TRUE,
    VersionInfo = list(iSEE = structure(
        list(c(2L, 10L, 0L)),
        class = c(
            "package_version",
            "numeric_version"
        )
    )),
    PanelId = c(ComplexHeatmapPlot = 1L),
    PanelHeight = 600L,
    PanelWidth = 7L,
    SelectionBoxOpen = FALSE,
    RowSelectionSource = "---",
    ColumnSelectionSource = "---",
    RowSelectionDynamicSource = FALSE,
    ColumnSelectionDynamicSource = FALSE,
    RowSelectionRestrict = FALSE,
    ColumnSelectionRestrict = FALSE,
    SelectionHistory = list()
)

################################################################################
# Settings for Row data table 1
################################################################################

initial[["RowDataTable1"]] <- new(
    "RowDataTable",
    Selected = "SHANK3",
    Search = "SHANK3",
    SearchColumns = c(
        "",
        "", "", "", "", "", ""
    ),
    HiddenColumns = character(0),
    VersionInfo = list(iSEE = structure(
        list(c(2L, 10L, 0L)),
        class = c(
            "package_version",
            "numeric_version"
        )
    )),
    PanelId = c(RowDataTable = 1L),
    PanelHeight = 600L,
    PanelWidth = 5L,
    SelectionBoxOpen = FALSE,
    RowSelectionSource = "---",
    ColumnSelectionSource = "---",
    DataBoxOpen = FALSE,
    RowSelectionDynamicSource = FALSE,
    ColumnSelectionDynamicSource = FALSE,
    RowSelectionRestrict = FALSE,
    ColumnSelectionRestrict = FALSE,
    SelectionHistory = list()
)

################################################################################
# Settings for Feature assay plot 1
################################################################################

initial[["FeatureAssayPlot1"]] <- new(
    "FeatureAssayPlot",
    Assay = "logcounts",
    XAxis = "Column data",
    XAxisColumnData = "diagnosis",
    XAxisFeatureName = "SHANK3",
    XAxisFeatureSource = "---",
    XAxisFeatureDynamicSource = FALSE,
    YAxisFeatureName = "SHANK3",
    YAxisFeatureSource = "RowDataTable1",
    YAxisFeatureDynamicSource = TRUE,
    FacetRowBy = "None",
    FacetColumnBy = "None",
    FacetRowByColData = "SpD",
    FacetColumnByColData = "SpD",
    ColorByColumnData = "SpD",
    ColorByFeatureNameAssay = "logcounts",
    ColorBySampleNameColor = "#FF0000",
    ShapeByColumnData = "SpD",
    SizeByColumnData = "age",
    TooltipColumnData = character(0),
    ShapeBy = "None",
    SizeBy = "None",
    ColorBy = "Column data",
    ColorByDefaultColor = "#000000",
    ColorByFeatureName = "SHANK3",
    ColorByFeatureSource = "---",
    ColorByFeatureDynamicSource = FALSE,
    ColorBySampleName = "Br1204",
    ColorBySampleSource = "---",
    ColorBySampleDynamicSource = FALSE,
    SelectionAlpha = 0.1,
    ZoomData = numeric(0),
    BrushData = list(),
    VisualBoxOpen = FALSE,
    VisualChoices = "Color",
    ContourAdd = FALSE,
    ContourColor = "#0000FF",
    PointSize = 2,
    PointAlpha = 1,
    Downsample = FALSE,
    DownsampleResolution = 200,
    CustomLabels = FALSE,
    CustomLabelsText = "Br1204",
    FontSize = 1.5,
    LegendPointSize = 3,
    LegendPosition = "Bottom",
    HoverInfo = TRUE,
    LabelCenters = FALSE,
    LabelCentersBy = "SpD",
    LabelCentersColor = "#000000",
    VersionInfo = list(iSEE = structure(
        list(c(2L, 10L, 0L)),
        class = c("package_version", "numeric_version")
    )),
    PanelId = c(FeatureAssayPlot = 1L),
    PanelHeight = 600L,
    PanelWidth = 7L,
    SelectionBoxOpen = FALSE,
    RowSelectionSource = "---",
    ColumnSelectionSource = "---",
    DataBoxOpen = FALSE,
    RowSelectionDynamicSource = FALSE,
    ColumnSelectionDynamicSource = FALSE,
    RowSelectionRestrict = FALSE,
    ColumnSelectionRestrict = FALSE,
    SelectionHistory = list()
)


################################################################################
# Settings for Feature assay plot 2
################################################################################

initial[["FeatureAssayPlot2"]] <- new(
    "FeatureAssayPlot",
    Assay = "logcounts",
    XAxis = "Column data",
    XAxisColumnData = "MitoRatio",
    XAxisFeatureName = "SHANK3",
    XAxisFeatureSource = "---",
    XAxisFeatureDynamicSource = FALSE,
    YAxisFeatureName = "SHANK3",
    YAxisFeatureSource = "RowDataTable1",
    YAxisFeatureDynamicSource = TRUE,
    FacetRowBy = "None",
    FacetColumnBy = "Column data",
    FacetRowByColData = "SpD",
    FacetColumnByColData = "SpD",
    ColorByColumnData = "diagnosis",
    ColorByFeatureNameAssay = "logcounts",
    ColorBySampleNameColor = "#FF0000",
    ShapeByColumnData = "SpD",
    SizeByColumnData = "age",
    TooltipColumnData = character(0),
    ShapeBy = "None",
    SizeBy = "None",
    ColorBy = "Column data",
    ColorByDefaultColor = "#000000",
    ColorByFeatureName = "SHANK3",
    ColorByFeatureSource = "---",
    ColorByFeatureDynamicSource = FALSE,
    ColorBySampleName = "Br1204",
    ColorBySampleSource = "---",
    ColorBySampleDynamicSource = FALSE,
    SelectionAlpha = 0.1,
    ZoomData = numeric(0),
    BrushData = list(),
    VisualBoxOpen = FALSE,
    VisualChoices = "Color",
    ContourAdd = FALSE,
    ContourColor = "#0000FF",
    PointSize = 2,
    PointAlpha = 1,
    Downsample = FALSE,
    DownsampleResolution = 200,
    CustomLabels = FALSE,
    CustomLabelsText = "Br1204",
    FontSize = 1.5,
    LegendPointSize = 3,
    LegendPosition = "Bottom",
    HoverInfo = TRUE,
    LabelCenters = FALSE,
    LabelCentersBy = "SpD",
    LabelCentersColor = "#000000",
    VersionInfo = list(iSEE = structure(
        list(c(2L, 10L, 0L)),
        class = c("package_version", "numeric_version")
    )),
    PanelId = c(FeatureAssayPlot = 2L),
    PanelHeight = 600L,
    PanelWidth = 12L,
    SelectionBoxOpen = FALSE,
    RowSelectionSource = "---",
    ColumnSelectionSource = "---",
    DataBoxOpen = FALSE,
    RowSelectionDynamicSource = FALSE,
    ColumnSelectionDynamicSource = FALSE,
    RowSelectionRestrict = FALSE,
    ColumnSelectionRestrict = FALSE,
    SelectionHistory = list()
)

################################################################################
# Settings for Feature assay plot 3
################################################################################

initial[["FeatureAssayPlot3"]] <- new(
    "FeatureAssayPlot",
    Assay = "logcounts",
    XAxis = "Column data",
    XAxisColumnData = "diagnosis",
    XAxisFeatureName = "SHANK3",
    XAxisFeatureSource = "---",
    XAxisFeatureDynamicSource = FALSE,
    YAxisFeatureName = "SHANK3",
    YAxisFeatureSource = "RowDataTable1",
    YAxisFeatureDynamicSource = TRUE,
    FacetRowBy = "None",
    FacetColumnBy = "Column data",
    FacetRowByColData = "SpD",
    FacetColumnByColData = "SpD",
    ColorByColumnData = "SpD",
    ColorByFeatureNameAssay = "logcounts",
    ColorBySampleNameColor = "#FF0000",
    TooltipColumnData = character(0),
    ShapeBy = "None",
    ShapeByColumnData = "SpD",
    SizeBy = "Column data",
    SizeByColumnData = "MitoRatio",
    ColorBy = "Column data",
    ColorByDefaultColor = "#000000",
    ColorByFeatureName = "SHANK3",
    ColorByFeatureSource = "---",
    ColorByFeatureDynamicSource = FALSE,
    ColorBySampleName = "Br1204",
    ColorBySampleSource = "---",
    ColorBySampleDynamicSource = FALSE,
    SelectionAlpha = 0.1,
    ZoomData = numeric(0),
    BrushData = list(),
    VisualBoxOpen = FALSE,
    VisualChoices = "Color",
    ContourAdd = FALSE,
    ContourColor = "#0000FF",
    PointSize = 2,
    PointAlpha = 1,
    Downsample = FALSE,
    DownsampleResolution = 200,
    CustomLabels = FALSE,
    CustomLabelsText = "Br1204",
    FontSize = 1.5,
    LegendPointSize = 3,
    LegendPosition = "Bottom",
    HoverInfo = TRUE,
    LabelCenters = FALSE,
    LabelCentersBy = "SpD",
    LabelCentersColor = "#000000",
    VersionInfo = list(iSEE = structure(
        list(c(2L, 10L, 0L)),
        class = c("package_version", "numeric_version")
    )),
    PanelId = c(FeatureAssayPlot = 3L),
    PanelHeight = 600L,
    PanelWidth = 7L,
    SelectionBoxOpen = FALSE,
    RowSelectionSource = "---",
    ColumnSelectionSource = "---",
    DataBoxOpen = FALSE,
    RowSelectionDynamicSource = FALSE,
    ColumnSelectionDynamicSource = FALSE,
    RowSelectionRestrict = FALSE,
    ColumnSelectionRestrict = FALSE,
    SelectionHistory = list()
)

################################################################################
# Settings for Feature assay plot 4
################################################################################

initial[["FeatureAssayPlot4"]] <- new(
    "FeatureAssayPlot",
    Assay = "logcounts",
    XAxis = "Column data",
    XAxisColumnData = "SpD",
    XAxisFeatureName = "SHANK3",
    XAxisFeatureSource = "---",
    XAxisFeatureDynamicSource = FALSE,
    YAxisFeatureName = "SHANK3",
    YAxisFeatureSource = "RowDataTable1",
    YAxisFeatureDynamicSource = TRUE,
    FacetRowBy = "None",
    FacetColumnBy = "None",
    FacetRowByColData = "SpD",
    FacetColumnByColData = "SpD",
    ColorBy = "Column data",
    ColorByColumnData = "SpD",
    ColorByFeatureNameAssay = "logcounts",
    ColorBySampleNameColor = "#FF0000",
    TooltipColumnData = character(0),
    ShapeBy = "Column data",
    ShapeByColumnData = "diagnosis",
    SizeBy = "Column data",
    SizeByColumnData = "MitoRatio",
    ColorByDefaultColor = "#000000",
    ColorByFeatureName = "SHANK3",
    ColorByFeatureSource = "---",
    ColorByFeatureDynamicSource = FALSE,
    ColorBySampleName = "Br1204",
    ColorBySampleSource = "---",
    ColorBySampleDynamicSource = FALSE,
    SelectionAlpha = 0.1,
    ZoomData = numeric(0),
    BrushData = list(),
    VisualBoxOpen = FALSE,
    VisualChoices = "Color",
    ContourAdd = FALSE,
    ContourColor = "#0000FF",
    PointSize = 2,
    PointAlpha = 1,
    Downsample = FALSE,
    DownsampleResolution = 200,
    CustomLabels = FALSE,
    CustomLabelsText = "Br1204",
    FontSize = 1.5,
    LegendPointSize = 3,
    LegendPosition = "Bottom",
    HoverInfo = TRUE,
    LabelCenters = FALSE,
    LabelCentersBy = "SpD",
    LabelCentersColor = "#000000",
    VersionInfo = list(iSEE = structure(
        list(c(2L, 10L, 0L)),
        class = c("package_version", "numeric_version")
    )),
    PanelId = c(FeatureAssayPlot = 4L),
    PanelHeight = 600L,
    PanelWidth = 5L,
    SelectionBoxOpen = FALSE,
    RowSelectionSource = "---",
    ColumnSelectionSource = "---",
    DataBoxOpen = FALSE,
    RowSelectionDynamicSource = FALSE,
    ColumnSelectionDynamicSource = FALSE,
    RowSelectionRestrict = FALSE,
    ColumnSelectionRestrict = FALSE,
    SelectionHistory = list()
)

